valor1=input("valor 1: ")
valor2=input("valor 2: ")
valor3=input("valor 3: ")

suma=float(valor1)+float(valor2)+float(valor3)
resta=float(valor1)-float(valor2)-float(valor3)
multiplicacion=float(valor1)*float(valor2)*float(valor3)
division=(float(valor1)/float(valor2))/float(valor3)
print("suma")
print(suma)
print("resta")
print(resta)
print("multiplicacion")
print(multiplicacion)
print("division")
print(division)